// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id        uint64      `json:"id"        ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
	DeletedAt *gtime.Time `json:"deletedAt" ` //
	Name      string      `json:"name"      ` // 用户姓名
	Gender    uint        `json:"gender"    ` // 用户性别
	Mobile    string      `json:"mobile"    ` // 用户电话
	Password  string      `json:"password"  ` // 用户密码
}
