version: "3.9"
services:
  dev:
    build:
      context: ./src/script
      dockerfile: Dockerfile_dev

    restart: unless-stopped
    volumes:
      - ./:/root/project/mall-gf-dapr
    stdin_open: true
    tty: true
  db:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./_data/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 3307:80
  casdoor:
    image: casbin/casdoor@sha256:466a495dd6bfee08caf3d42249722139f41ac4bee9ef708b9294bfab4e0e7f69
    restart: unless-stopped
    ports:
    - 18000:18000
    volumes:
      - ./src/script/casdoor/app.conf:/conf/app.conf