version: "3.9"
services:
  dev:
    image: 117503445/dev-golang
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./:/root/project/mall-gf-dapr
    stdin_open: true
    tty: true