// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Pay is the golang structure of table pay for DAO operations like Where/Data.
type Pay struct {
	g.Meta     `orm:"table:pay, do:true"`
	Id         interface{} //
	CreatedAt  *gtime.Time //
	UpdatedAt  *gtime.Time //
	DeletedAt  *gtime.Time //
	ConsumerId interface{} // 消费者的 UUID | "44ec60c4-1434-47a6-a9c2-443eb1ac27c8"
	OrderId    interface{} // 订单 id
	Status     interface{} // 订单状态
}
