// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Product is the golang structure of table product for DAO operations like Where/Data.
type Product struct {
	g.Meta    `orm:"table:product, do:true"`
	Id        interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	DeletedAt *gtime.Time //
	Name      interface{} // 产品名称
	Desc      interface{} // 产品描述
	Stock     interface{} // 产品库存
	Price     interface{} // 产品金额
	CreatorId interface{} // 创建者的 UUID | "44ec60c4-1434-47a6-a9c2-443eb1ac27c8"
}
