apiVersion: apps/v1
kind: Deployment
metadata:
  name: casdoor
  namespace: mall-gf-dapr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casdoor
  template:
    metadata:
      labels:
        app: casdoor
    spec:
      containers:
      - name: casdoor
        image: casbin/casdoor:v1.152.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: "/conf"
            name: config
      volumes:
      - configMap:
          name: casdoor-config
        name: config
---