apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: mall-gf-dapr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: 117503445/mall-gf-dapr-product
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---