// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Product is the golang structure for table product.
type Product struct {
	Id        uint64      `json:"id"        ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
	DeletedAt *gtime.Time `json:"deletedAt" ` //
	Name      string      `json:"name"      ` // 产品名称
	Desc      string      `json:"desc"      ` // 产品描述
	Stock     uint        `json:"stock"     ` // 产品库存
	Price     uint        `json:"price"     ` // 产品金额
	CreatorId string      `json:"creatorId" ` // 创建者的 UUID | "44ec60c4-1434-47a6-a9c2-443eb1ac27c8"
}
